baseURL = 'https://xiaweiqiang.com/'
locale = 'zh-cn'
title = '夏卫强'
copyright = "©夏卫强"
theme = 'PaperMod'

[pagination]
  pagerSize = 10

[params]
  author = "夏卫强"
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  disableSpecial1stPost = true
  DateFormat = "2006/01/02"
  comments = false
  hideFooter = true
  hideMeta = true         # 全局关闭默认文章元数据
  mainSections = ["ignore_me"]    # 隐藏首页的历史文章列表

  [params.label]
    text = "夏卫强"

  [params.profileMode]
    enabled = false

# 顶部产品目录导航
[[menu.main]]
    name = "创作"
    url = "/create/"
    weight = 1
[[menu.main]]
    name = "工作"
    url = "/services/"
    weight = 2
[[menu.main]]
    name = "体验"
    url = "/experience/"
    weight = 3

# 解除 Hugo 默认的安全限制
[markup.goldmark.renderer]
  unsafe = true

# 彻底关闭系统默认的分类和标签列表（极致纯净）
disableKinds = ["taxonomy", "term"]